{
 "title": "Wilder dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Profiles found",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  updated_at AS \"time\",\n  value\nFROM fetchq_sys_metrics\nWHERE\n  $__timeFilter(updated_at) AND\n  queue = 'profile' AND\n  metric = 'cnt'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Profiles processed",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  updated_at AS \"time\",\n  value\nFROM fetchq_sys_metrics\nWHERE\n  $__timeFilter(updated_at) AND\n  queue = 'profile' AND\n  metric = 'prc'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Profiles Error",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  updated_at AS \"time\",\n  value\nFROM fetchq_sys_metrics\nWHERE\n  $__timeFilter(updated_at) AND\n  queue = 'profile' AND\n  metric = 'err'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Posts processed",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  updated_at AS \"time\",\n  value\nFROM fetchq_sys_metrics\nWHERE\n  $__timeFilter(updated_at) AND\n  queue = 'post' AND\n  metric = 'cnt'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Posts processed",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  updated_at AS \"time\",\n  value\nFROM fetchq_sys_metrics\nWHERE\n  $__timeFilter(updated_at) AND\n  queue = 'post' AND\n  metric = 'prc'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Posts Errors",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  updated_at AS \"time\",\n  value\nFROM fetchq_sys_metrics\nWHERE\n  $__timeFilter(updated_at) AND\n  queue = 'post' AND\n  metric = 'err'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Profiles",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  created_at AS \"time\",\n  metric AS metric,\n  value\nFROM fetchq__profile__metrics\nWHERE\n  $__timeFilter(created_at)"
    }
   ]
  },
  {
   "title": "Posts",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  created_at AS \"time\",\n  metric AS metric,\n  value\nFROM fetchq__post__metrics\nWHERE\n  $__timeFilter(created_at)"
    }
   ]
  }
 ]
}