version: '2.1'
services:

    postgres:
        image: fetchq/fetchq:9.6-1.3.0
        ports:
            - ${PG_PORT:-5432}:5432
        environment:
            POSTGRES_USER: ${PG_USER:-wilder}
            POSTGRES_PASSWORD: ${PG_PASSWORD:-wilder}
            POSTGRES_DB: ${PG_DB:-wilder}
        volumes:
            - ${HUMBLE_DATA}/pg:/var/lib/postgresql/data

    grafana:
        image: grafana/grafana:5.4.3
        ports:
            - ${GRAFANA_PORT-3000}:3000
        environment:
            - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-grafana}
            - GF_SERVER_ROOT_URL=${GRAFANA_URL:-http://grafana:3000/}
        volumes:
            - ${HUMBLE_DATA}/grafana:/var/lib/grafana

    wilder:
        image: node:9.9
        depends_on:
            - postgres
        environment:
            LOG_LEVEL: ${LOG_LEVEL:-verbose}
            NODE_ENV: ${NODE_ENV:-development}
            EXPRESS_PORT: ${EXPRESS_PORT:-8080}
            PG_PORT: ${PG_PORT:-5432}
            PG_HOST: ${PG_HOST:-postgres}
            PG_DB: ${PG_DB:-wilder}
            PG_PASSWORD: ${PG_PASSWORD:-wilder}
            PG_USER: ${PG_USER:-wilder}
        volumes:
            - ./services/wilder:/usr/src/app
        working_dir: /usr/src/app
        entrypoint: [ "yarn", "start" ]